name: Feature request
description: Suggest an improvement
body:
  - type: textarea
    attributes: {label: Problem, description: What developer problem should this solve?}
    validations: {required: true}
  - type: textarea
    attributes: {label: Proposed approach}
